spring:
  resources:
    static-locations: file:/static/
  datasource:
    username: gordonuser
    password: gordonpass
    hikari:
      maximum-pool-size: 20
  jpa:
    show_sql: true
---
spring:
  profiles: postgres
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://database:5432/atsea
---
spring:
  profiles: mysql
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://database:3306/atsea
---
spring:
  profiles: sqlserver
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlserver://database:1433;databaseName=atsea